# ndarray数组的创建方法

- 从列表、元祖等类型创建ndarray
- 使用NumPy函数创建ndarray，如arange, ones, zeros等
- 从字节流（raw bytes）中创建ndarray
- 从文件中读取特定格式，创建ndarray

# 从列表、元祖等类型创建ndarray

- 形式：np.array(list/tuple, dtype=np.int32)
- 当不指定dtype时，NumPy将根据数据情况自动关联一个dtype

# 使用NumPy中的函数创建ndarray

- np.arange(n) 类似range()函数，元素从0到n-1
- np.ones(shape) 根据shape生成一个全1数组，shape是元祖类型
- np.zeros(shape) 根据shape生成一个全0数组，shape是元祖类型
- np.full(shape, val) 根据shape生成一个数组，每个元素值都是val
- np.eye(n) 创建一个正方的n * n单位矩阵，对角线是1，其余为0
- np.ones_like(a) 根据数组a的形状生成一个全1的数组
- np.zeros_like(a) 根据数组a的形状生成一个全0的数组
- np.full_like(a, val) 根据数组a的形状生成一个数组，每个元素值都是val
- np.linspace() 根据起止数据等间距地填充数据，形成数组
- np.concatenate() 将两个或多个数组合并成一个新的数组

In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.full((3, 3), 'x')

array([['x', 'x', 'x'],
       ['x', 'x', 'x'],
       ['x', 'x', 'x']], dtype='<U1')

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])