# ndarray的维度变换

- reshape(shape) 不改变数组元素，返回一个shape形状的数组，原数组不变
- resize(shape) 与reshape()功能一致，但修改原数组
- swapaxes(ax1, ax2) 将数组n个维度中两个维度进行调换
- flatten() 对数组进行降维，返回折叠后的一维数组，原数组不变

In [1]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
# 总元素个数与变换前一致
a.reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# 此处相当于行列转置
a.swapaxes(0, 1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [10]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# ndarray的类型变换

- astype(new_type) 会创建新的数组，即使与原数组类型一致
- tolist() 转换成列表

In [11]:
a.astype(np.float32)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [12]:
a.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]