In [2]:
import numpy as np

# 数组的索引和切片

- **索引：** 获取数组中特定位置元素的过程
- **切片：** 获取数组子集的过程

In [3]:
# 一维数组的索引和切片：与Python的列表操作类似

a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 索引，获取第3个元素
a[2]

2

In [6]:
# 切片，起始编号 : 终止编号（不含） : 步长
a[1:7:2]

array([1, 3, 5])

In [7]:
# 多维数组的索引

b = np.arange(24).reshape((2, 3, 4))

b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
# 每个维度一个索引值，使用逗号分隔
b[1, 1, 2]

18

In [16]:
# 多维数组的切片，可在每个维度上分别进行切片
b[1:2]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
b[1:2, 1:3]

array([[[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
b[1:2, 1:3, 1:3]

array([[[17, 18],
        [21, 22]]])