# 迭代数组

- 迭代器对象numpy.nditer提供了一种灵活访问一个或者多个数组元素的方式

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
# 默认行序优先 C-order
for x in np.nditer(a):
    print(x, end=',')

0,1,2,3,4,5,

In [4]:
# 指定列序优先
for x in np.nditer(a, order='F'):
    print(x, end=',')

0,3,1,4,2,5,

- 修改数组中元素的值
  - nditer 对象有另一个可选参数 op_flags
  - 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only）
  - 为了在遍历数组的同时，实现对数组元素值的修改，必须指定 readwrite 或者 writeonly 的模式

In [5]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
# 把数组中的每个元素都变为原来的2倍
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * 2  # 省略号是惯例索引，表示对数组的所有元素进行操作
    
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

- 广播迭代
  - 如果两个数组是可广播的， nditer组合对象能够同时迭代它们

In [8]:
a = np.arange(12).reshape(3, 4)
b = np.array([10, 20, 30, 40], dtype=int)

# 数组b被广播到a的大小
for x,y in np.nditer([a, b]):
    print('{0}:{1}'.format(x,y), end=',')

0:10,1:20,2:30,3:40,4:10,5:20,6:30,7:40,8:10,9:20,10:30,11:40,

- 使用数组元素迭代器 flat

In [9]:
a = np.arange(12).reshape(3, 4)

for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [10]:
for x in a.flat:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
