In [1]:
import numpy as np

# append

- numpy.append(arr, values, axis=None)
- append 函数在数组的末尾添加值，追加操作会分配整个数组，并把原来的数组复制到新数组中
- 输入数组的维度必须匹配否则将生成ValueError

In [3]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.append(a, [7, 8, 9])
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 沿轴0添加：列数要相同
b0 = np.append(a, [[7, 8, 9]], axis=0)
b0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# 沿轴1添加：数组加在右边，行数要相同
b1 = np.append(a, [[7, 8, 9], [10, 11, 12]], axis=1)
b1

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# insert

- numpy.insert(arr, obj, values, axis)
- insert 函数在给定索引之前，沿给定轴在目标数组中插入值

In [12]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# 未传入axis参数，在插入之前目标数组会被展开
b = np.insert(a, 3, [7, 8])
b

array([1, 2, 3, 7, 8, 4, 5, 6])

In [16]:
# 沿轴0广播
b0 = np.insert(a, 1, [7], axis=0)
b0

array([[1, 2],
       [7, 7],
       [3, 4],
       [5, 6]])

In [17]:
# 沿轴1广播
b1 = np.insert(a, 1, 8, axis=1)
b1

array([[1, 8, 2],
       [3, 8, 4],
       [5, 8, 6]])

# delete

- Numpy.delete(arr, obj, axis)
- delete 函数返回从输入数组中删除指定子数组的新数组
- 与 insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开

In [18]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# 未传递axis参数，数组将被展开
b = np.delete(a, 5)
b

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [22]:
# 删除第二行
b0 = np.delete(a, 1, axis=0)
b0

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [21]:
# 删除第二列
b1 = np.delete(a, 1, axis=1)
b1

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

# unique

- unique 函数用于去除数组中的重复元素
- numpy.unique(arr, return_index, return_inverse, return_counts)
  - arr：输入数组，如果不是一维数组则会展开
  - return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式存储
  - return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式存储
  - return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数

In [23]:
a = np.array([1, 2, 2, 3, 3, 3, 4, 5, 5, 6])

b = np.unique(a)
b

array([1, 2, 3, 4, 5, 6])

In [24]:
u, indices = np.unique(a, return_index=True)

indices

array([0, 1, 3, 6, 7, 9], dtype=int64)