# NumPy的I/O

Numpy 可以读写磁盘上的文本数据或二进制数据

In [1]:
import numpy as np

# CSV

- Comma-Separated Value, 逗号分隔值
- CSV是一种常见的文件格式，用来存储批量数据

# 使用CSV进行一维和二维数据的存取

`np.savetxt(frame, array, fmt='%.18e', delimiter=None)`
- frame 文件、字符串或产生器，可以是.gz或.bz2的压缩文件
- array 存入文件的数组
- fmt 写入文件的格式，如%d, %.2f, %.18e
- delimiter 分隔字符串，默认是任何空格

`np.loadtxt(frame, dtype=np.float, delimiter=None, unpack=False)`
- frame 文件、字符串或产生器，可以是.gz或.bz2的压缩文件
- dtype 数据类型，可选
- delimiter 分隔字符串，默认是任何空格
- unpack 如果True, 读入属性将分别写入不同变量

In [7]:
n = np.arange(100).reshape((5, 20))

# 把数组存入csv文件
np.savetxt('nums.csv', n, fmt='%.1f', delimiter=',')

# 从csv文件读取数组
np.loadtxt('nums.csv', dtype=np.int, delimiter=',')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

# 多维数据的存取

`n.tofile(frame, sep='', format='%s')`
- frame 文件、字符串
- sep 数据分隔字符串，如果是空串，写入文件为二进制
- format 写入数据的格式

`np.fromfile(frame, dtype=float, count=-1, sep='')`
- frame 文件、字符串
- dtype 读取的数据类型
- count 读入元素的个数，-1表示读入整个文件
- sep 数据分隔字符串，如果是空串，写入文件为二进制

In [12]:
n = np.arange(100).reshape((5, 10, 2))

# 把多维数组存入数据文件
n.tofile('nums.dat', sep=',', format='%d')

# 从数据文件中读取多维数组
np.fromfile('nums.dat', dtype=np.float, sep=',').reshape((5, 10, 2))

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.]],

       [[20., 21.],
        [22., 23.],
        [24., 25.],
        [26., 27.],
        [28., 29.],
        [30., 31.],
        [32., 33.],
        [34., 35.],
        [36., 37.],
        [38., 39.]],

       [[40., 41.],
        [42., 43.],
        [44., 45.],
        [46., 47.],
        [48., 49.],
        [50., 51.],
        [52., 53.],
        [54., 55.],
        [56., 57.],
        [58., 59.]],

       [[60., 61.],
        [62., 63.],
        [64., 65.],
        [66., 67.],
        [68., 69.],
        [70., 71.],
        [72., 73.],
        [74., 75.],
        [76., 77.],
        [78., 79.]],

       [[80., 81.],
        [82., 83.],
        [84., 85.],
        [86., 87.],
        [88., 89.],
        [90., 91.],
        [92., 93.],
        [94., 95.],
        [96., 97.],
        [98.

# NumPy的便捷文件存取

`np.save(fname, array) 或 np.savez(fname, array)`
- fname 文件名，以.npy为扩展名，压缩扩展名为.npz
- array 数组变量

`np.load(fname)`
- fname 文件名，以.npy为扩展名，压缩扩展名为.npz

In [13]:
n = np.arange(100).reshape((5, 10, 2))

np.save('nums.npy', n)

np.load('nums.npy')

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])