# Numpy的统计函数

- sum(a, axis=None) 根据给定轴axis计算数组a相关元素之和，axis整数或元祖
- mean(a, axis=None) 根据给定轴axis计算数组a相关元素的期望，axis整数或元祖
- average(a, axis=None, weights=None) 根据给定轴axis计算数组a相关元素的加权平均值
- std(a, axis=None) 根据给定轴axis计算数组a相关元素的标准差
- var(a, axis=None) 根据给定轴axis计算数组a相关元素的方差
- max(a) min(a) 计算数组a中元素的最大值、最小值
- argmax(a) argmin(a) 计算数组a中元素最大值、最小值的降一维后下标
- unravel_index(index, shape) 根据shape将一维下标index转换成多维下标
- ptp(a) 计算数组a中元素最大值和最小值的差
- median(a) 计算数组a中元素的中位数（中值）

*`axis=None`是统计函数的标配参数*

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 求和
np.sum(a)

105

In [4]:
# 求给定轴的期望
np.mean(a, axis=1)

array([ 2.,  7., 12.])

In [5]:
# axis=0表示列
np.mean(a, axis=0)

array([5., 6., 7., 8., 9.])

In [6]:
# 求加权平均值
np.average(a, axis=0, weights=[10, 5, 1])

# 2*10 + 7*5 + 1*12 / (10+5+1) = 4.1875

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [7]:
# 求标准差
np.std(a)

4.320493798938574

In [8]:
# 求方差
np.var(a)

18.666666666666668

In [9]:
b = np.arange(15, 0, -1).reshape(3, 5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [10]:
# 最大值
np.max(b)

15

In [12]:
# 扁平化后的下标
np.argmax(b)

0

In [13]:
# 重塑成多维下标
np.unravel_index(np.argmax(b), b.shape)

(0, 0)

In [14]:
# 求最大值和最小值之间的差
np.ptp(b)

14

In [15]:
# 求中位数
np.median(b)

8.0