In [1]:
import numpy as np

In [2]:
# 打印当前numpy的版本
print(np.__version__)

1.19.2


In [7]:
# 构造一个全零矩阵，并打印其占用的内存大小
a = np.zeros((10, 10))
print('{0} bytes'.format(a.size * a.itemsize))

800 bytes


In [9]:
# 创建一个数组，并将其倒序
a = np.arange(0, 10, 1)
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
# 获取数组中非0值的索引
np.nonzero([1, 0, 3, 5, 0, 0, 7, 9])

(array([0, 2, 3, 6, 7], dtype=int64),)

In [12]:
# 构造一个3*3的矩阵，其值均为1， 并在最外层加两圈0
a = np.ones((3,3))
a = np.pad(a, pad_width=2, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [19]:
# 对矩阵做归一化操作
a = np.random.randint(0, 100, (5, 5))
max_val = a.max()
min_val = a.min()
a = (a - min_val)/(max_val - min_val)
a

array([[0.32978723, 0.21276596, 0.06382979, 0.4893617 , 0.10638298],
       [0.64893617, 0.90425532, 0.4787234 , 0.55319149, 0.21276596],
       [0.91489362, 0.        , 0.89361702, 0.27659574, 0.0106383 ],
       [0.14893617, 0.36170213, 0.53191489, 0.23404255, 0.22340426],
       [0.0106383 , 0.54255319, 0.58510638, 1.        , 0.96808511]])

In [21]:
# 找到两个数组中相同的值
a1 = np.random.randint(0, 10, 5)
a2 = np.random.randint(0, 10, 5)
print(a1)
print(a2)
print(np.intersect1d(a1, a2))

[1 7 2 8 4]
[4 0 1 8 5]
[1 4 8]


In [22]:
# 获取今天、昨天、明天的日期
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print('today', today)
print('yesterday', yesterday)
print('tomorrow', tomorrow)

today 2021-01-25
yesterday 2021-01-24
tomorrow 2021-01-26


In [24]:
# 获取一个月中的所有天
np.arange('2021-01', '2021-02', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

In [25]:
# 让数组的值不能被改变
a = np.zeros(5)
a.flags.writeable = False

In [33]:
# 找到在一个数组中，最接近一个数的值
a1 = np.arange(100)
a2 = np.random.uniform(0, 100)
print(a2)
i = (np.abs(a1-a2)).argmin()
print(a1[i])

37.313584448567525
37


In [34]:
# 打印数组元素的坐标和值
a = np.arange(9).reshape(3, 3)
for i, v in np.ndenumerate(a):
    print(i, v)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [41]:
# 按照数组的某一列进行排序
a = np.random.randint(0, 10, (3, 3))
print(a)
print(a[a[:, 0].argsort()])  # 按照第1列的值从小到大排列

[[1 8 1]
 [5 9 1]
 [4 3 7]]
[[1 8 1]
 [4 3 7]
 [5 9 1]]


In [42]:
# 统计数组中每个数值出现的次数
a = np.array([1, 2, 3, 1, 1, 2, 4, 5, 3, 5])
np.bincount(a)

array([0, 3, 2, 2, 1, 2], dtype=int64)

In [44]:
# 对一个四维数组的最后两维求和
a = np.random.randint(0, 10, (4, 4, 4 ,4))
a.sum(axis=(-2, -1))

array([[65, 75, 73, 65],
       [78, 59, 77, 76],
       [67, 62, 83, 61],
       [81, 68, 80, 72]])

In [46]:
# 查找数组中出现次数最多的值
a = np.random.randint(0, 10, 50)
print(np.bincount(a).argmax())

3


In [50]:
# 快速查找topN
a = np.arange(10000)
np.random.shuffle(a)
n = 5
print(a[np.argpartition(-a, n)[:n]])

[9997 9999 9998 9996 9995]


In [8]:
# 打印一个函数的帮助文档
print(help(np.info(np.sum)))

 sum(*args, **kwargs)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same precision as the platform integer is used.
out : ndarray, optional
